name: Markdownlint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule: [{ cron: "0 6 * * *" }]
permissions:
  contents: read
jobs:
  markdownlint:
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: "**/*.md" 
