name: MegaLinter
on:
  push: { branches: [main] }
  pull_request: { branches: [main] }
  workflow_dispatch:
permissions:
  contents: read
  pull-requests: write
  statuses: write
jobs:
  megalinter:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: oxsecurity/megalinter/flavors/cupcake@v8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLY_FIXES: none
